"""Initial migration with document_chunks table

Revision ID: afe456c4fa28
Revises:
Create Date: 2026-02-04 15:19:26.966419

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "afe456c4fa28"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create pgvector extension first
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(dim=1536), nullable=False),
        sa.Column("source_file", sa.String(length=255), nullable=False),
        sa.Column("heading_path", sa.Text(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.Column(
            "chunk_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_chunks_id"), "document_chunks", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_source_file"),
        "document_chunks",
        ["source_file"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Create vector index for faster similarity search
    # Using HNSW instead of IVFFlat for better accuracy with medium-sized datasets
    op.execute(
        """
        CREATE INDEX document_chunks_embedding_idx 
        ON document_chunks 
        USING hnsw (embedding vector_cosine_ops)
    """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop vector index
    op.execute("DROP INDEX IF EXISTS document_chunks_embedding_idx")

    op.drop_index(op.f("ix_document_chunks_source_file"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    # ### end Alembic commands ###
